package com.nequard.location;
import com.nequard.auth.OrganizationAccessService;import jakarta.validation.Valid;import jakarta.validation.constraints.NotBlank;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/v1/locations") public class LocationController{
 private final LocationRepository repo;private final OrganizationAccessService access;public LocationController(LocationRepository r,OrganizationAccessService a){repo=r;access=a;}
 record Request(@NotBlank String name,UUID organizationId,String address,Double latitude,Double longitude){}
 @GetMapping public List<Location> all(Authentication a,@RequestParam(required=false) UUID organizationId){UUID org=access.isSuperAdmin(a)?organizationId:access.currentOrganization(a);return org==null?repo.findAll():repo.findByOrganizationId(org);}
 @GetMapping("/{id}") public ResponseEntity<Location> one(Authentication a,@PathVariable UUID id){return repo.findById(id).filter(l->access.canAccess(a,l.getOrganizationId())).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());}
 @PostMapping @PreAuthorize("hasAnyRole('SUPER_ADMIN','NETWORK_ADMIN')") public ResponseEntity<?> create(Authentication a,@RequestBody @Valid Request r){try{UUID org=access.requireOrganization(a,r.organizationId());Location l=new Location();l.setName(r.name());l.setOrganizationId(org);l.setAddress(r.address());l.setLatitude(r.latitude());l.setLongitude(r.longitude());return ResponseEntity.status(HttpStatus.CREATED).body(repo.save(l));}catch(SecurityException|IllegalArgumentException e){return ResponseEntity.status(HttpStatus.FORBIDDEN).body(Map.of("error",e.getMessage()));}}
 @DeleteMapping("/{id}") @PreAuthorize("hasAnyRole('SUPER_ADMIN','NETWORK_ADMIN')") public ResponseEntity<Void> delete(Authentication a,@PathVariable UUID id){return repo.findById(id).filter(l->access.canAccess(a,l.getOrganizationId())).map(l->{repo.delete(l);return ResponseEntity.noContent().<Void>build();}).orElse(ResponseEntity.notFound().build());}
}