package com.nequard.auth;
public enum Role { SUPER_ADMIN, NETWORK_ADMIN, NETWORK_ENGINEER, TECHNICIAN, NOC_OPERATOR, SECURITY_ANALYST, MANAGER, AUDITOR, VIEWER, COMMUNITY_ADMIN, COMMUNITY_USER, INTERNET_PROVIDER }
