package com.nequard.network;
import jakarta.persistence.*;import java.time.Instant;import java.util.UUID;
@Entity @Table(name="devices",indexes={@Index(name="idx_devices_org",columnList="organization_id"),@Index(name="idx_devices_location",columnList="location_id")})
public class Device{
 @Id @GeneratedValue(strategy=GenerationType.UUID) UUID id;
 @Column(name="organization_id",nullable=false) UUID organizationId;
 @Column(name="location_id") UUID locationId;
 @Column(nullable=false) String hostname; String managementIp,macAddress,vendor,model,serialNumber,osVersion,firmwareVersion,building,room,managementProtocol,monitoringStatus="PENDING",operationalStatus="UNKNOWN";
 @Enumerated(EnumType.STRING) @Column(nullable=false) DeviceType deviceType;
 Double latitude,longitude,cpuPercent,memoryPercent,temperatureC,powerWatts; Long uptimeSeconds;
 Instant lastSeenAt,createdAt=Instant.now(),updatedAt=Instant.now();
 public UUID getId(){return id;} public UUID getOrganizationId(){return organizationId;} public void setOrganizationId(UUID v){organizationId=v;} public UUID getLocationId(){return locationId;} public void setLocationId(UUID v){locationId=v;}
 public String getHostname(){return hostname;}public void setHostname(String v){hostname=v;}public String getManagementIp(){return managementIp;}public void setManagementIp(String v){managementIp=v;}public String getMacAddress(){return macAddress;}public void setMacAddress(String v){macAddress=v;}public DeviceType getDeviceType(){return deviceType;}public void setDeviceType(DeviceType v){deviceType=v;}public String getVendor(){return vendor;}public void setVendor(String v){vendor=v;}public String getModel(){return model;}public void setModel(String v){model=v;}public String getSerialNumber(){return serialNumber;}public void setSerialNumber(String v){serialNumber=v;}public String getOsVersion(){return osVersion;}public void setOsVersion(String v){osVersion=v;}public String getFirmwareVersion(){return firmwareVersion;}public void setFirmwareVersion(String v){firmwareVersion=v;}public String getBuilding(){return building;}public void setBuilding(String v){building=v;}public String getRoom(){return room;}public void setRoom(String v){room=v;}public String getManagementProtocol(){return managementProtocol;}public void setManagementProtocol(String v){managementProtocol=v;}public String getMonitoringStatus(){return monitoringStatus;}public void setMonitoringStatus(String v){monitoringStatus=v;}public String getOperationalStatus(){return operationalStatus;}public void setOperationalStatus(String v){operationalStatus=v;}
 public Double getLatitude(){return latitude;}public void setLatitude(Double v){latitude=v;}public Double getLongitude(){return longitude;}public void setLongitude(Double v){longitude=v;}public Double getCpuPercent(){return cpuPercent;}public void setCpuPercent(Double v){cpuPercent=v;}public Double getMemoryPercent(){return memoryPercent;}public void setMemoryPercent(Double v){memoryPercent=v;}public Double getTemperatureC(){return temperatureC;}public void setTemperatureC(Double v){temperatureC=v;}public Double getPowerWatts(){return powerWatts;}public void setPowerWatts(Double v){powerWatts=v;}public Long getUptimeSeconds(){return uptimeSeconds;}public void setUptimeSeconds(Long v){uptimeSeconds=v;}public Instant getLastSeenAt(){return lastSeenAt;}public void setLastSeenAt(Instant v){lastSeenAt=v;}public Instant getCreatedAt(){return createdAt;}public Instant getUpdatedAt(){return updatedAt;}
}