package com.nequard.network;
import com.nequard.auth.OrganizationAccessService;import jakarta.validation.Valid;import jakarta.validation.constraints.NotBlank;import jakarta.validation.constraints.NotNull;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController @RequestMapping("/api/v1/devices") public class DeviceController{
 private final DeviceRepository repo;private final OrganizationAccessService access;public DeviceController(DeviceRepository r,OrganizationAccessService a){repo=r;access=a;}
 record Request(@NotBlank String hostname,@NotNull UUID organizationId,UUID locationId,String managementIp,String macAddress,DeviceType deviceType,String vendor,String model,String serialNumber,String osVersion,String firmwareVersion,String building,String room,String managementProtocol,Double latitude,Double longitude){}
 @GetMapping public List<Device> all(Authentication a,@RequestParam(required=false) UUID organizationId){UUID org=access.isSuperAdmin(a)?organizationId:access.currentOrganization(a);return org==null?repo.findAll():repo.findByOrganizationId(org);}
 @GetMapping("/{id}") public ResponseEntity<Device> one(Authentication a,@PathVariable UUID id){return repo.findById(id).filter(d->access.canAccess(a,d.getOrganizationId())).map(ResponseEntity::ok).orElse(ResponseEntity.notFound().build());}
 @PostMapping @PreAuthorize("hasAnyRole('SUPER_ADMIN','NETWORK_ADMIN','NETWORK_ENGINEER')") public ResponseEntity<?> create(Authentication a,@RequestBody @Valid Request r){try{UUID org=access.requireOrganization(a,r.organizationId());Device d=new Device();d.setHostname(r.hostname());d.setOrganizationId(org);d.setLocationId(r.locationId());d.setManagementIp(r.managementIp());d.setMacAddress(r.macAddress());d.setDeviceType(r.deviceType()==null?DeviceType.OTHER:r.deviceType());d.setVendor(r.vendor());d.setModel(r.model());d.setSerialNumber(r.serialNumber());d.setOsVersion(r.osVersion());d.setFirmwareVersion(r.firmwareVersion());d.setBuilding(r.building());d.setRoom(r.room());d.setManagementProtocol(r.managementProtocol());d.setLatitude(r.latitude());d.setLongitude(r.longitude());return ResponseEntity.status(HttpStatus.CREATED).body(repo.save(d));}catch(SecurityException|IllegalArgumentException e){return ResponseEntity.status(HttpStatus.FORBIDDEN).body(Map.of("error",e.getMessage()));}}
 @DeleteMapping("/{id}") @PreAuthorize("hasAnyRole('SUPER_ADMIN','NETWORK_ADMIN')") public ResponseEntity<Void> delete(Authentication a,@PathVariable UUID id){return repo.findById(id).filter(d->access.canAccess(a,d.getOrganizationId())).map(d->{repo.delete(d);return ResponseEntity.noContent().<Void>build();}).orElse(ResponseEntity.notFound().build());}
}