CREATE TABLE organizations (
 id UUID PRIMARY KEY,
 name VARCHAR(160) NOT NULL,
 slug VARCHAR(160) NOT NULL UNIQUE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE locations (
 id UUID PRIMARY KEY,
 organization_id UUID NOT NULL REFERENCES organizations(id),
 name VARCHAR(160) NOT NULL,
 address VARCHAR(300),
 latitude DOUBLE PRECISION,
 longitude DOUBLE PRECISION,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE devices (
 id UUID PRIMARY KEY,
 organization_id UUID NOT NULL REFERENCES organizations(id),
 location_id UUID REFERENCES locations(id),
 hostname VARCHAR(160) NOT NULL,
 management_ip INET,
 device_type VARCHAR(40) NOT NULL,
 vendor VARCHAR(120),
 model VARCHAR(120),
 monitoring_status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
 operational_status VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN',
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 last_seen_at TIMESTAMPTZ
);
CREATE INDEX idx_devices_org ON devices(organization_id);
CREATE INDEX idx_devices_status ON devices(operational_status);
